# -*- coding: utf-8 -*-
"""
Created on Sat Mar 17 17:59:37 2018

@author: Connor
"""


# %% Import Modules ===========================================================

import numpy as np
import time
import datetime
import logging

import os
import sys
sys.path.append(os.getcwd())

from Drivers.Logging import EventLog as log

from Drivers.StateMachine import ThreadFactory, Machine

from Drivers.VISA.SRS import SIM960
from Drivers.VISA.Thorlabs import MDT639B

from Drivers.DAQ.Tasks import AiTask


# %% Helper Functions =========================================================

'''The following are helper functionss that increase the readablity of code in
    this script. These functions are defined by the user and should not
    directly appear in the main loop of the state machine.'''

# Update a 1D circular buffer -------------------------------------------------
@log.log_this()
def update_buffer(buffer, new_data, length):
    length = int(abs(length))
    buffer = np.append(buffer, new_data)
    if buffer.size > length:
        buffer = buffer[-length:]
    return buffer

# Periodic Timer --------------------------------------------------------------
@log.log_this()
def get_lap(time_interval):
    return int(time.time() // time_interval)


# %% Initialization ===========================================================

sm = Machine()


# %% Databases and Settings ===================================================

# Communications queue --------------------------------------------------------
'''The communications queue is a couchbase queue that serves as the
intermediary between this script and others. The entries in this queue
are parsed as commands in this script:
    Requesting to change state:
        {'state': {<state DB path>:{'state':<state>},...}}
    Requesting to change device settings:
        {'device_setting': {<device driver DB path>:{<method name>:<args>,...},...}}
    Requesting to change a control parameter:
        {'control_parameter': {<parameter name>:<value>,...}}
-Commands are sent into the queue by setting the "message" keyword argument
within the CouchbaseDB queue.push() method. 
-Commands are read from the queue with the queue.pop() method.
-If the DB path given does not exist in the defined STATE_DBs and
DEVICE_DBs, or the given method and parameter does not exist in 
CONTROL_PARAMS, no attempt is made to excecute the command.
-All commands are caught and logged at the INFO level.
-Multiple commands may be input simultaneously by nesting single commands
within the 'state', 'device_setting', and 'control_parameter' keys:
    message = {
        'state':{<state DB path>:{'state':<state>},...},
        'device_setting':{<device driver DB path>:{<method name>:<args>,...},...},
        'control_parameter':{<parameter name>:<value>,...}}
'''
COMMS = 'filter_cavity'
sm.init_comms(COMMS)

# Internal database names --------------------------------------------------------
'''The following are all of the databases that this script directly
controls. Each of these databases are initialized within this script.
The databases should be grouped by function:
    state:
        -The entries in state databases should reflect the current state of
        the system and the level of compliance. Other scripts should look
        to these databases in order to resolve prerequisites.
    device:
        -The entries in visa databases should include the settings for
        each unique device or device/channel combination.
    monitor:
        -The entries in monitor databases should contain secondary 
        variables used to determine compliance with the state of the 
        system, and to determine any actions required to maintain
        compliance. 
        -In general, data for use in control loops should have
        an updated value every 0.2 seconds. Data for passive monitoring
        should have a relaxed 1.0 second or longer update period.
    log:
        -This should be a single database that serves as the repository of
        all logs generated by this script.
    control:
        -This should be a single database that contains all control loop 
        variables accessible to commands from the comms queue.
'''
STATE_DBs = [
    'filter_cavity/state']
DEVICE_DBs =[
    'filter_cavity/device_PID', 'filter_cavity/device_HV',
    'filter_cavity/device_DAQ_Vout_vs_reflect']
MONITOR_DBs = [
    'filter_cavity/PID_output', 'filter_cavity/PID_output_limits',
    'filter_cavity/PID_action', 'filter_cavity/HV_output',
    'filter_cavity/DAQ_Vout_vs_reflect']
LOG_DB = 'filter_cavity/log'
CONTROL_DB = 'filter_cavity/control'
MASTER_DBs = STATE_DBs + DEVICE_DBs + MONITOR_DBs + [LOG_DB] + [CONTROL_DB]
sm.init_master_DB_names(STATE_DBs, DEVICE_DBs, MONITOR_DBs, LOG_DB, CONTROL_DB)

# External database names -----------------------------------------------------
'''This is a list of all databases external to this control script that are 
    needed to check prerequisites'''
R_STATE_DBs = []
R_DEVICE_DBs =[]
R_MONITOR_DBs = ['filter_cavity/TEC_temperature', 'filter_cavity/DAQ_error_signal']
READ_DBs = R_STATE_DBs + R_DEVICE_DBs + R_MONITOR_DBs
sm.init_read_DB_names(R_STATE_DBs, R_DEVICE_DBs, R_MONITOR_DBs)

# Default settings ------------------------------------------------------------
'''A template for all settings used in this script. Upon initialization 
these settings are checked against those saved in the database, and 
populated if found empty. Each state and device database should be
represented. 
-Default values are only added to a database if the setting keys are not
found within the database (if the database has not yet been initialized
with that setting).
-For device databases, default settings of None are populated with values
from the device, but set values are written to the device. All
initialized settings are read from the device at startup.
-Include all settings that need to be tracked in the database:
    states:
        -Entries in the state databases are specified as follows:
            {<state database path>:{
            'state':<name of the current state>,
            'prerequisites':{
                    'critical':<critical>,
                    'necessary':<necessary>,
                    'optional':<optional>},
            'compliance':<compliance of current state>
            'desired_state':<name of the desired state>,
            'initialized':<initialization state of the control script>,
            'heartbeat':<datetime.datetime.utcnow()>},...}
        -The state name should correspond to one of the defined states.
        -The prerequisites should be a 3 part dictionary of boolean values
        that indicates whether the prerequisites pass for the current
        state. The 3 severity levels are critical, necessary, and optional.
        -The compliance level should be a boolean value that indicates
        whether the system is compliant with the current state.
        -The "desired_state" is mostly for internal use, particularly for
        cases where the state is temporarliy changed. The script should
        seek to bring the current state to the desired state. The script 
        should not change the current state if the desired state is
        undefined.
        -The "initialized" parameter is a boolean value that indicates that
        the current state is accurate. This is useful for cases where a
        master program or watchdog starts the control scripts. It should
        be set to False by the master program before the control scripts
        are executed, and should only be set to True after the
        control scripts have determined the current state. In order to 
        smoothly connect to the system if the instruments are already 
        running, initialization prerequisites should be either
        "necessary" or "optional" ("critical" would force the "safe" state).
        -The "heartbeat" parameter is a datetime.datetime utc timestamp
        that indicates when the control script last checked the state.
        Every time the control script finishes a loop it writes the state
        db to the buffer with a new heartbeat value. This is useful to
        determine if the current state in the database is "stale". The 
        heartbeat is only incidentally updated in the record as items are 
        written to it in the coarse of normal control script operation.
    devices:
        -Entries in the device databases are specified as follows:
            {<device database path>:{
                'driver':<driver class>,
                'queue':<queue name>,
                '__init__':<args>,
                <method name>:<args>,...},...}
        -The entries should include the settings for each unique device
        or device/channel combination. 
        -The "driver" should contain an uninitialized instance of the
        driver class
        -The "queue" should contain the name of the device queue. The queue
        is needed to coordinate access to the devices. Each blocking
        connection to a device should have a unique queue name. If access
        to one part of an instrument blocks access to other parts, that set
        of parts should all use the same unique queue. A good queue name is
        the instrument address.
        -The "__init__" method should hold all arguments necessary to 
        initialize the device driver.
        -For automation purposes, the setting names and parameters should
        be derived from the names of the device driver methods.
        -Single arguments should be entered as is:
            <method name>:<arg>
        -Place multiple arguments in a list containing a list of positional
        arguments and a dictionary of keyword arguments:
            <method name>:[[<args>], {<kwargs>}]
            <method name>:[[<args>]]
            <method name>:[{<kwargs>}]
        -A setting of None calls the methods without any arguments. Device
        drivers should reserve such cases for getting the current device
        settings:
            <method name>:None -> returns current device settings
        -The automated "send_args()" checks for the above cases before
        parsing and sending the commands.
    control parameter:
        -Entries in the control parameter database are specified as
        follows:
            {<control database path>:{
                <control parameter>:{'value':<value>,'type':<type str>},...}}
        -Control parameters have both a value and a type.
        -Only include parameters that should have remote access. There is
        no protection against the insertion of bad values.
        -The "main_loop" parameter is reserved for operation of the
        state machine.
'''
STATE_SETTINGS = {
        'filter_cavity/state':{
                'state':'engineering',
                'prerequisites':{
                        'critical':False,
                        'necessary':False,
                        'optional':False},
                'compliance':False,
                'desired_state':'lock',
                'initialized':False,
                'heartbeat':datetime.datetime.utcnow()}}
DEVICE_SETTINGS = {
        # VISA device settings
        'filter_cavity/device_PID':{
                'driver':SIM960,
                'queue':'ASRL1',
                '__init__':[['ASRL1::INSTR', 3]],
                'proportional_action':True, 'integral_action':True,
                'derivative_action':False, 'offset_action':None, 'offset':None,
                'proportional_gain':-0.2, 'integral_gain':1.0e2, 'pid_action':None,
                'external_setpoint_action':False, 'internal_setpoint':0.000,
                'ramp_action':False, 'manual_output':None,
                'upper_output_limit':2.00, 'lower_output_limit':0.00, 'power_line_frequency':60},
        'filter_cavity/device_HV':{
                'driver':MDT639B,
                'queue':'ASRL30',
                '__init__':[['ASRL30::INSTR']], 'master_scan_action':False,
                'y_min_limit':0.00, 'y_max_limit':150.00, 'y_voltage':99.1},
        # DAQ settings
        'filter_cavity/device_DAQ_Vout_vs_reflect':{
                'driver':AiTask,
                'queue':'DAQ_ai',
                '__init__':[
                    [[{'physical_channel':'Dev1/ai1', 'terminal_config':'NRSE',
                       'min_val':-1.0, 'max_val':1.0}],
                        250e3, int(250e3*0.01)],{'timeout':5.0}],
                'reserve_cont':False, 'reserve_point':False}}
CONTROL_PARAMS = {CONTROL_DB:{}}
SETTINGS = dict(list(STATE_SETTINGS.items()) + list(DEVICE_SETTINGS.items()) + list(CONTROL_PARAMS.items()))
sm.init_default_settings(STATE_SETTINGS, DEVICE_SETTINGS, CONTROL_PARAMS)


# %% Initialize Databases, Devices, and Settings ==============================

# Connect to MongoDB ----------------------------------------------------------
'''Creates a client and connects to all defined databases'''
db = {}
sm.init_DBs(db=db)

# Start Logging ---------------------------------------------------------------
'''Initializes logging for this script. If the logging database is unset then
    all logs will be output to the stout. When the logging database is set
    there are two logging handlers, one logs lower threshold events to the log 
    buffer and the other logs warnings and above to the permanent log database.
    The threshold for the base logger, and the two handlers, may be set in the
    following command.'''
sm.init_logging(database_object=db[LOG_DB], logger_level=logging.INFO, log_buffer_handler_level=logging.DEBUG, log_handler_level=logging.WARNING)

# Initialize all Devices and Settings -----------------------------------------
'''This initializes all device drivers and checks that all settings
(as listed in SETTINGS) exist within the databases. Any missing
settings are populated with the default values.
-If the setting does not exist within a device database that setting is
propogated to the device, otherwise the local settings are read from the
device.
-The "driver" settings are saved as strings.
-The settings for "__init__" methods are are not sent or pulled to devices.
-A local copy of all settings is contained within the local_settings
dictionary.
-Each device database should be associated with a driver and a queue. The 
format is as follows:
    dev[<device database path>] = {
            'driver':<driver object>,
            'queue':<queue objecct>}
'''
dev = {}
local_settings={}
sm.init_device_drivers_and_settings(dev=dev, local_settings=local_settings)

# Initialize Local Copy of Monitors -------------------------------------------
'''This initializes all device drivers and checks that all settings
(as listed in SETTINGS) exist within the databases. Any missing
settings are populated with the default values. This function 
automatically restarts if an error is encoutered.
-If the setting does not exist within a device database that setting is
propogated to the device, otherwise the local settings are read from the
device.
-The "driver" settings are saved as strings.
-The settings for "__init__" methods are are not sent or pulled to devices.
-A local copy of all settings is contained within the local_settings
dictionary.
-Each device database should be associated with a driver and a queue. The 
format is as follows:
    dev[<device database path>] = {
            'driver':<driver object>,
            'queue':<queue objecct>}
'''
mon = {}
    # SRS -----------------------------
mon['filter_cavity/PID_action'] = {
        'data':np.array([]),
        'device':dev['filter_cavity/device_PID'],
        'new':False}
mon['filter_cavity/PID_output'] = {
        'data':np.array([]),
        'device':dev['filter_cavity/device_PID'],
        'new':False}
mon['filter_cavity/PID_output_limits'] = {
        'data':{'max':local_settings['filter_cavity/device_PID']['upper_output_limit'],
                'min':local_settings['filter_cavity/device_PID']['lower_output_limit']},
        'device':dev['filter_cavity/device_PID'],
        'new':False}
    # HV Piezo ------------------------
mon['filter_cavity/HV_output'] = {
        'data':np.array([]),
        'device':dev['filter_cavity/device_HV'],
        'new':False}
    # DAQ -----------------------------
mon['filter_cavity/DAQ_Vout_vs_reflect'] = {
        'data':np.array([]),
        'device':dev['filter_cavity/device_DAQ_Vout_vs_reflect'],
        'new':False}
    # External ------------------------
sm.init_monitors(mon=mon)


# %% State Functions ==========================================================

# Global Variables ------------------------------------------------------------
timer = {}
array = {}
thread = {}

# Do nothing function ---------------------------------------------------------
'''A functional placeholder for cases where nothing should happen.'''
@log.log_this()
def nothing(state_db):
    pass


# %% Monitor Functions ========================================================
'''This section is for defining the methods needed to monitor the system.'''

# SRS Data --------------------------------------------------------------------
array['srs:v_out'] = np.array([])
srs_record_interval = 10 # seconds
timer['srs:record'] = get_lap(srs_record_interval)
def get_srs_data():
# Get lap number
    new_record_lap = get_lap(srs_record_interval)
# Pull data from SRS ----------------------------------
    device_db = 'filter_cavity/device_PID'
    # Wait for queue
    dev[device_db]['queue'].queue_and_wait()
    # Get values --------------------------------
         # Output voltage -------------
    new_v_out = dev[device_db]['driver'].new_output_monitor()
    if new_v_out:
        v_out = dev[device_db]['driver'].output_monitor()
        # Output voltage limits -------
    v_min = dev[device_db]['driver'].lower_limit
    v_max = dev[device_db]['driver'].upper_limit
        # PID action ------------------
    pid_action = dev[device_db]['driver'].pid_action()
    # Remove from queue
    dev[device_db]['queue'].remove()
    # Update buffers and databases ----------
        # Output voltage --------------
    if new_v_out:
        mon['filter_cavity/PID_output']['new'] = True
        mon['filter_cavity/PID_output']['data'] = update_buffer(
                mon['filter_cavity/PID_output']['data'],
                v_out, 500)
            # Write to the buffer
        db['filter_cavity/PID_output'].write_buffer({'V':v_out})
            # Append to the record array
        array['srs:v_out'] = np.append(array['srs:v_out'], v_out)
        if new_record_lap > timer['srs:record']:
            # Record statistics
            db['filter_cavity/PID_output'].write_record({
                    'V':array['srs:v_out'].mean(),
                    'std':array['srs:v_out'].std(),
                    'n':array['srs:v_out'].size})
            # Empty the array
            array['srs:v_out'] = np.array([])
        # Voltage limits ----------
    if (mon['filter_cavity/PID_output_limits']['data'] != {'min':v_min, 'max':v_max}):
        mon['filter_cavity/PID_output_limits']['new'] = True
        mon['filter_cavity/PID_output_limits']['data'] = {'min':v_min, 'max':v_max}
        db['filter_cavity/PID_output_limits'].write_record_and_buffer({'min':v_min, 'max':v_max})
        # PID action --------------
    if (mon['filter_cavity/PID_action']['data'] != pid_action):
        mon['filter_cavity/PID_action']['new'] = True
        mon['filter_cavity/PID_action']['data'] = pid_action
        db['filter_cavity/PID_action'].write_record_and_buffer({'Action':pid_action})
    # Propogate lap numbers ---------------------------------------------
    if new_record_lap > timer['srs:record']:
        timer['srs:record'] = new_record_lap
thread['get_srs_data'] = ThreadFactory(target=get_srs_data)

# HV Data ---------------------------------------------------------------------
array['hv:v_out'] = np.array([])
hv_record_interval = 10 # seconds
timer['hv:record'] = get_lap(hv_record_interval)
def get_HV_data():
# Get lap number
    new_record_lap = get_lap(hv_record_interval)
# Pull data from Thorlabs 3-axis piezo controller -----
    device_db = 'filter_cavity/device_HV'
    # Wait for queue
    dev[device_db]['queue'].queue_and_wait()
    # Get values
    hv_out = dev[device_db]['driver'].y_voltage()
    # Remove from queue
    dev[device_db]['queue'].remove()
    # Update buffers and databases ----------
    mon['filter_cavity/HV_output']['new'] = True
    mon['filter_cavity/HV_output']['data'] = update_buffer(
            mon['filter_cavity/HV_output']['data'],
            hv_out, 100)
    db['filter_cavity/HV_output'].write_buffer({'V':hv_out})
    # Append to the record array
    array['hv:v_out'] = np.append(array['hv:v_out'], hv_out)
    if new_record_lap > timer['hv:record']:
        # Record statistics
        db['filter_cavity/HV_output'].write_record({
                'V':array['hv:v_out'].mean(),
                'std':array['hv:v_out'].std(),
                'n':array['hv:v_out'].size})
        # Empty the array
        array['hv:v_out'] = np.array([])
    # Propogate lap numbers ---------------------------------------------
    if new_record_lap > timer['hv:record']:
        timer['hv:record'] = new_record_lap
thread['get_HV_data'] = ThreadFactory(target=get_HV_data)

# Monitor ---------------------------------------------------------------------
control_interval = 0.5 # s
passive_interval = 1.0 # s
timer['monitor:control'] = get_lap(control_interval)
timer['monitor:passive'] = get_lap(passive_interval)
def monitor(state_db):
# Get lap number
    new_control_lap = get_lap(control_interval)
    new_passive_lap = get_lap(passive_interval)
# Update control loop variables -------------------------------------
    if (new_control_lap > timer['monitor:control']):
        thread_name = 'get_srs_data'
        (alive, error) = thread[thread_name].check_thread()
        if error != None:
            raise error
        if not(alive):
        # Start new thread
            thread[thread_name].start()
    # Pull data from external databases -------------------
        new_data = []
        for doc in mon['filter_cavity/DAQ_error_signal']['cursor']:
            new_data.append(doc['V'])
         # Update buffers -----------------------
        if len(new_data) > 0:
            mon['filter_cavity/DAQ_error_signal']['new'] = True
            mon['filter_cavity/DAQ_error_signal']['data'] = update_buffer(
                mon['filter_cavity/DAQ_error_signal']['data'],
                new_data, 500)
    # Propogate lap numbers ---------------------------------------------
        timer['monitor:control'] = new_control_lap
# Update passive monitoring variables -------------------------------
    if (new_passive_lap > timer['monitor:passive']):
        thread_name = 'get_HV_data'
        (alive, error) = thread[thread_name].check_thread()
        if error != None:
            raise error
        if not(alive):
        # Start new thread
            thread[thread_name].start()
    # Pull data from external databases -------------------
        new_data = []
        for doc in mon['filter_cavity/TEC_temperature']['cursor']:
            new_data.append(doc['V'])
         # Update buffers -----------------------
        if len(new_data) > 0:
            mon['filter_cavity/TEC_temperature']['new'] = True
            mon['filter_cavity/TEC_temperature']['data'] = update_buffer(
                mon['filter_cavity/TEC_temperature']['data'],
                new_data, 500)
    # Propogate lap numbers ---------------------------------------------
        timer['monitor:passive'] = new_passive_lap


# %% Search Functions =========================================================
'''This section is for defining the methods needed to bring the system into
    its defined states.'''

# Find Lock -------------------------------------------------------------------
from scipy.interpolate import UnivariateSpline
from scipy.optimize import minimize
v_range_threshold = 0.1 #(limit-threshold)/(upper - lower limits)
log_setpoint_error_interval = 60*10 #s
lock_hold_interval = 1.0 #s
timer['find_lock:locked'] = time.time()
timer['find_lock:log_setpoint_error'] = time.time()
def find_lock(state_db, last_good_position=None):
    mod_name = __name__
    func_name = find_lock.__name__
# Queue the SRS PID controller --------------------------------------
    device_db = 'filter_cavity/device_PID'
    dev[device_db]['queue'].queue_and_wait(priority=True)
# Initialize threshold variables ------------------------------------
    v_high = (1-v_range_threshold)*dev[device_db]['driver'].upper_limit + v_range_threshold*dev[device_db]['driver'].lower_limit
    v_low = (1-v_range_threshold)*dev[device_db]['driver'].lower_limit + v_range_threshold*dev[device_db]['driver'].upper_limit
# Quick relock ------------------------------------------------------
    # Re-engage the lock at the last know position --------
    if last_good_position is not None:
        '''This is used to quicklyre-engage the lock starting from a known
        posistion. This is only activated if "last_good_position" is given as a 
        keyword argument to this function call. The state then skips the first
        round of lock tests.'''
        settings_list = [
                {'manual_output':last_good_position},
                {'pid_action':False},
                {'offset_action':True,'offset':last_good_position},
                {'pid_action':True}] # TODO: add delay?
        sm.update_device_settings(device_db, settings_list)
    # Update lock timer -----------------------------------
        timer['find_lock:locked'] = time.time()
        locked = True
# Check if locked ---------------------------------------------------
    elif dev[device_db]['driver'].pid_action():
        '''This is the main logic used to determine if the current state is
        locked. The main check is that the current output is within the
        accepted range between the upper and lower hardware limits.'''
    # PID is enabled
        current_output = dev[device_db]['driver'].output_monitor()
        if (current_output < v_low) or (current_output > v_high):
        # Output is beyond voltage thresholds
            locked = False
        else:
        # Lock is holding
            locked = True
    else:
    # PID is disabled
        locked = False
# If locked ---------------------------------------------------------            
    if locked:
        '''If the current state passed the previous tests the control script
        holds off on making a final judgement until the specified interval has
        passed since lock acquisition.'''
    # Remove the SRS PID controller from queue ------------
        dev[device_db]['queue'].remove()
    # Check lock interval ---------------------------------
        if (time.time() - timer['find_lock:locked']) > lock_hold_interval:
        # TODO: if reflect error signal is high -> locked = False
        # Lock is succesful, update state variable
            current_state[state_db]['compliance'] = True
            db[state_db].write_record_and_buffer(current_state[state_db])
            log_str = ' filter_cavity lock successful'
            log.log_info(mod_name, func_name, log_str)
        # Update the monitor variable if necessary
            if (mon['filter_cavity/PID_action']['data'] != True):
                mon['filter_cavity/PID_action']['new'] = True
                mon['filter_cavity/PID_action']['data'] = True
                db['filter_cavity/PID_action'].write_record_and_buffer({'Action':True})
# If unlocked -------------------------------------------------------
    else:
        '''The current state has failed the lock tests. The PID controller is
        then broght into a known state, and the DAQ is used to find the lock
        point.'''
    # Reset the PID controller ----------------------------
        settings_list = [
                {'pid_action':False},
                {'upper_output_limit':STATES[state_db][current_state[state_db]['state']]['settings'][device_db]['upper_output_limit'],
                 'lower_output_limit':STATES[state_db][current_state[state_db]['state']]['settings'][device_db]['lower_output_limit']}]
        sm.update_device_settings(device_db, settings_list)
        settings_list = [
                {'y_min_limit':STATES[state_db][current_state[state_db]['state']]['settings']['filter_cavity/device_HV']['y_min_limit'],
                 'y_max_limit':STATES[state_db][current_state[state_db]['state']]['settings']['filter_cavity/device_HV']['y_max_limit']},
                 {'y_voltage':STATES[state_db][current_state[state_db]['state']]['settings']['filter_cavity/device_HV']['y_voltage']}]
        sm.update_device_settings('filter_cavity/device_HV', settings_list)
    # Reinitialize threshold variables --------------------
        v_high = (1-v_range_threshold)*dev[device_db]['driver'].upper_limit + v_range_threshold*dev[device_db]['driver'].lower_limit
        v_low = (1-v_range_threshold)*dev[device_db]['driver'].lower_limit + v_range_threshold*dev[device_db]['driver'].upper_limit
    # Reset the piezo hysteresis --------------------------
        dev[device_db]['driver'].manual_output(v_low)
    # Queue the DAQ ---------------------------------------
        daq_db = 'filter_cavity/device_DAQ_Vout_vs_reflect'
        dev[daq_db]['queue'].queue_and_wait(priority=True)
    # Get lock point data ---------------------------------
        x = np.linspace(v_low, v_high, 200)
        y = np.copy(x)
        w = np.copy(x)
        for ind, x_val in enumerate(x):
        # Touch queue (prevent timeout) ---------
            dev[device_db]['queue'].touch()
            dev[daq_db]['queue'].touch()
        # Change position and trigger DAQ -------
            dev[device_db]['driver'].manual_output(x_val)
            data = dev[daq_db]['driver'].read_point()
            # Average and Std ---------
            y[ind] = np.mean(data)
            w[ind] = 1/np.std(data)
        # Release and remove the DAQ from queue -
        dev[daq_db]['driver'].reserve_point(False)
        dev[daq_db]['queue'].remove()
        # Reset the piezo hysteresis ------------
        dev[device_db]['driver'].manual_output(x[0])
        # Update monitor DB ---------------------
        mon['filter_cavity/DAQ_Vout_vs_reflect']['new'] = True
        mon['filter_cavity/DAQ_Vout_vs_reflect']['data'] = np.array([x, y])
        db['filter_cavity/DAQ_Vout_vs_reflect'].write_record_and_buffer({'V_out':x.tolist(), 'V_ref':y.tolist()})
    # Estimate the lock point -----------------------------
        #Coarse Estimate ------------------------
        min_index = np.argmin(y)
        output_coarse = x[min_index]
        #Fine Estimate --------------------------
        try:
            spline = UnivariateSpline(x, y, w=w)
            min_result = minimize(spline, output_coarse)
            new_output = min_result['x'][0]
        except:
            log.log_exception(mod_name, func_name)
            new_output = output_coarse
    # Get Lock --------------------------------------------
        if (new_output > v_low) and (new_output < v_high):
            '''If the new lock point is within the acceptable range between
            the upper and lower hardware limits, attempt to lock.'''
            log_str = ' Estimated voltage setpoint = {:.3f}, locking.'.format(new_output)
            log.log_info(mod_name, func_name, log_str)
        # Update deivice settings ---------------
            settings_list = [{'manual_output':new_output,
                              'offset_action':True,
                              'offset':new_output},
                             {'pid_action':True}] #TODO: add delay?
            sm.update_device_settings(device_db, settings_list)
        # Remove the SRS PID controller from queue
            dev[device_db]['queue'].remove()
        # Update lock timer ---------------------
            timer['find_lock:locked'] = time.time()
        else:
            '''If not, something is wrong. This could be that the temperature
            control is not on, the temperature has not settled at the setpoint,
            or the temperature setpoint needs adjustment. Either way, there is
            no method to adjust those parameters'''
            log_setpoint_error_condition = ((time.time() - timer['find_lock:log_setpoint_error']) > log_setpoint_error_interval)
            if log_setpoint_error_condition:
                log_str = ' Estimated voltage setpoint = {:.3f}, lock unobtainable.'.format(new_output)
                log.log_critical(mod_name, func_name, log_str)
            # Update timer
                timer['find_lock:log_setpoint_error'] = time.time()

# Transfer to Manual ----------------------------------------------------------
def transfer_to_manual(state_db):
    mod_name = __name__
    func_name = keep_lock.__name__
# Queue the SRS PID controller --------------------------------------
    device_db = 'filter_cavity/device_PID'
    dev[device_db]['queue'].queue_and_wait()
# Check if the PID controller is on ---------------------------------
    if dev[device_db]['driver'].pid_action():
    # Get current output
        v_out = dev[device_db]['driver'].output_monitor()
    # Bumpless transfer to manual
        settings_list = [
                {'manual_output':v_out},
                {'pid_action':False}]
        sm.update_device_settings(device_db, settings_list)
# Remove SRS PID from queue -----------------------------------------
    dev[device_db]['queue'].remove()
# Update state variable
    current_state[state_db]['compliance'] = True
    db[state_db].write_record_and_buffer(current_state[state_db])
    log_str = ' Transfer to manual successful'
    log.log_info(mod_name, func_name, log_str)


# %% Maintain Functions =======================================================
'''This section is for defining the methods needed to maintain the system in
    its defined states.'''
    
# Keep Lock -------------------------------------------------------------------
v_std_threshold = 5 # standard deviations
lock_age_threshold = 30.0 #s
def keep_lock(state_db):
    mod_name = __name__
    func_name = keep_lock.__name__
    locked = True
# Evaluate conditions
    new_output_condition = mon['filter_cavity/PID_output']['new']
    lock_age_condition = ((time.time() - timer['find_lock:locked']) > lock_age_threshold)
    no_new_limits_condition = not(mon['filter_cavity/PID_output_limits']['new'])
# Get most recent values --------------------------------------------
    if new_output_condition:
        current_output = mon['filter_cavity/PID_output']['data'][-1]
    current_limits = mon['filter_cavity/PID_output_limits']['data']
    # Lock threshold
    v_high = (1-v_range_threshold)*current_limits['max'] + v_range_threshold*current_limits['min']
    v_low = (1-v_range_threshold)*current_limits['min'] + v_range_threshold*current_limits['max']
    # Clear 'new' data flags
    mon['filter_cavity/PID_output']['new'] = False
    mon['filter_cavity/PID_output_limits']['new'] = False
# Check if the PID controller is on ---------------------------------
    if (mon['filter_cavity/PID_action']['data'] != True):
    # It is not locked
        locked = False
        log_str = " filter_cavity lock lost, PID controller was disabled"
        log.log_error(mod_name, func_name, log_str)
# Check if the output is outside the acceptable range ---------------
    elif new_output_condition:
        if (current_output < v_low) or (current_output > v_high):
        # It is not locked
            locked = False
            log_str = " filter_cavity lock lost, output was outside the acceptable range"
            log.log_error(mod_name, func_name, log_str)
    # TODO: check error signal std
# If not locked -----------------------------------------------------
    if not(locked):
    # Update state variable
        current_state[state_db]['compliance'] = False
        db[state_db].write_record_and_buffer(current_state[state_db])
    # Check if quick relock is possible
        if (lock_age_condition and no_new_limits_condition):
        # Calculate the expected output voltage
            data = mon['filter_cavity/PID_output']['data'][:-1]
            v_avg = np.mean(data)
            v_avg_slope = np.mean(np.diff(data))/(len(data)-1)
            v_expected = v_avg + v_avg_slope*len(data)/2
        # Remove the last point from the local monitor
            mon['filter_cavity/PID_output']['data'] = data
        # Attempt a quick relock
            log_str = " Attempting quick relock"
            log.log_info(mod_name, func_name, log_str)
            find_lock(state_db, last_good_position=v_expected)
# If locked ---------------------------------------------------------
    else:
    # If the system is at a new lock point, reinitialize the local monitors
        if (not(lock_age_condition) and not(no_new_limits_condition)):
        # Reinitialize the output voltage monitor
            mon['filter_cavity/PID_output']['data'] = np.array([])
            mon['filter_cavity/PID_output']['new'] = False
    # If the system is at a stable lock point, adjust the hardware voltage limits
        elif (lock_age_condition and new_output_condition):
        # Calculate the new limit thresholds
            data = mon['filter_cavity/PID_output']['data']
            v_avg = np.mean(data)
            v_avg_slope = np.mean(np.diff(data))/(len(data)-1)
            v_expected = v_avg + v_avg_slope*len(data)/2
            v_std = np.std(data - v_avg_slope*np.arange(len(data)))
            new_upper_limit = round(v_expected + (v_std_threshold*v_std)/(1-2*v_range_threshold),2)
            new_lower_limit = round(v_expected - (v_std_threshold*v_std)/(1-2*v_range_threshold),2)
            if (new_upper_limit - new_lower_limit) < 0.5: #TODO: determine optimal thresholds
                new_upper_limit = round(v_expected + 0.25,2)
                new_lower_limit = round(v_expected - 0.25,2)
        # Restrict the limits
            device_db = 'filter_cavity/device_PID'
            state_limits = {
                    'upper_output_limit':STATES[state_db][current_state[state_db]['state']]['settings'][device_db]['upper_output_limit'],
                    'lower_output_limit':STATES[state_db][current_state[state_db]['state']]['settings'][device_db]['lower_output_limit']}
            if (new_upper_limit > state_limits['upper_output_limit']):
                new_upper_limit = state_limits['upper_output_limit']
            if (new_lower_limit < state_limits['lower_output_limit']):
                new_lower_limit = state_limits['lower_output_limit']
        # Determine if limits should be updated
            new_v_high = (1-v_range_threshold)*new_upper_limit + v_range_threshold*new_lower_limit
            new_v_low = (1-v_range_threshold)*new_lower_limit + v_range_threshold*new_upper_limit
            update_upper = False
            update_lower = False
            if new_v_high > current_limits['max']:
                update_upper = True
            if new_v_low < current_limits['min']:
                update_lower = True
            if new_upper_limit < v_high:
                update_upper = True
            if new_lower_limit > v_low:
                update_lower = True
            if (new_upper_limit == current_limits['max']):
                update_upper = False
            if (new_lower_limit == current_limits['min']):
                update_lower = False
            if new_upper_limit == new_lower_limit:
                update_upper = False
                update_lower = False
        # Update the hardware limits
            if (update_upper or update_lower):
            # Update the limits
                if not(update_lower):
                    settings_list = {'upper_output_limit':new_upper_limit}
                elif not(update_upper):
                    settings_list = {'lower_output_limit':new_lower_limit}
                else:
                    settings_list = {
                            'upper_output_limit':new_upper_limit,
                            'lower_output_limit':new_lower_limit}
                sm.update_device_settings(device_db, settings_list, write_log=False)
            # Update the voltage limit monitor
                mon['filter_cavity/PID_output_limits']['new'] = True
                mon['filter_cavity/PID_output_limits']['data'] = {'min':new_lower_limit, 'max':new_upper_limit}
                db['filter_cavity/PID_output_limits'].write_record_and_buffer({'min':new_lower_limit, 'max':new_upper_limit})
                log_str = " New output limits = {:}".format(mon['filter_cavity/PID_output_limits']['data'])
                log.log_info(mod_name, func_name, log_str)

# Lock Disabled ---------------------------------------------------------------
def lock_disabled(state_db):
    mod_name = __name__
    func_name = lock_disabled.__name__
    if (mon['filter_cavity/PID_action']['data'] != False):
    # Update state variable
        current_state[state_db]['compliance'] = False
        db[state_db].write_record_and_buffer(current_state[state_db])
        log_str = " Detected lock enabled, transfering to manual"
        log.log_info(mod_name, func_name, log_str)


# %% Operate Functions ========================================================
'''This section is for defining the methods called only when the system is in
    its defined states.'''


# %% States ===================================================================

'''Defined states are composed of collections of settings, prerequisites,
and routines:
    settings:
        -Only the settings particular to a state need to be listed, and
        they should be in the same format as those in SETTINGS:
            'settings':{
                <device database path>:{
                    <method>:<args>,...},...}
        -The settings listed here should be thought of as stationary
        prerequisites, or as known initialization states that the system
        should pass through to ease the transition to the compliant state.
        -Dynamic settings should be dealt with in the state's methods.
        -These settings will be applied before the system transitions from
        one state to the next.
        -Place groups of settings together in lists if the order of the
        operations matter. The groups of settings will be applied as
        ordered in the list:
            'settings':{
                <device database path>:[
                    {<first group>},{<second group>},...]
    prerequisites:
        -Prerequisites should be entered as lists of dictionaries that
        include the database and key:value pair that corresponds to a
        passing prerequisite for the given state:
            'prerequisites':{
                {'critical':[{
                    'db':<database path>,
                    'key':<entry's key>,
                    'test':<desired value>},...], 
                'necessary':[{...},...],
                'optional':[{...}]}}
        -The "test" should be a lambda function that evaluates to true
        if the prerequisite has passed.
        -The automated "from_keys()" checks for lists of keys needed to
        retrieve values from nested dictionaries.
        -Prereqs should be separated by severity:
            critical:
                -A failed critical prereq could jeopardize the health of
                the system if brought into or left in the applied state.
                -Critical prerequisites are continuously monitored.
                -The system is placed into a temporary "safe" state upon 
                failure of a critical prereq.
            necessary:
                -Failure of a necessary prereq will cause the system to 
                come out of, or be unable to reach, compliance.
                -Necessary prereqs are checked if the system is out
                of compliance.
                -The system is allowed to move into the applied state upon 
                failure of a necessary prereq, but no attempts are made to
                bring the system into compliance.
            optional:
                -Failure of an optional prereq should not cause failure
                elsewhere, but system performance or specifications can't
                be guaranteed. Think of it more as "non compulsory" than
                "optional".
                -Optional prereqs are checked when the system is out of
                compliance, and when the system is in compliance, but the
                optional prereqs are listed as failed.
                -The system is allowed to move into the applied state upon 
                failure of an optional prereq.
    routines:
        -The routines are the functions needed to monitor the state, bring
        the state into compliance, maintain the state in compliance, and
        operate any other scripts that require a compliant state. 
        -All routines must accept the path of a state DB as an argument:
            routine(<state database path>)
        -Only one function call should be listed for each method. The 
        methods themselves may call others.
        -Routines should be entered for the 4 cases:
            'routines':{
                'monitor':<method>, 'search':<method>,
                'maintain':<method>, 'operate':<method>}
        monitoring:
            -The monitor method should generally update all state 
            parameters necessary for the "search" or "maintain" methods as
            well as any secondary parameters useful for passive monitoring.
            -Updating state parameters includes getting new values from
            connected instruments and pulling new values from connected
            databases. 
            -New values from instruments should always be saved to their
            respective databases. The main entry in the database 
            should typically be keyed with the symbols for the units of the
            measurement (V, Hz, Ohm,...):
                db[device_db].write_record_and_buffer({<unit>:<value>})
            -Suggested refresh times for control loop parameters is 0.2
            seconds, while a 1.0 second or longer refresh time should be
            sufficient for passive monitoring parameters.
            -All values should be stored locally in circular buffers. The
            sizes of which should be controlled within these methods.
        searching:
            -The search method should be able to bring the system into
            compliance from any noncompliant state. 
            -The most important cases to consider are those starting from
            the configuration as given in the state's "settings", and the
            cases where the state has transitioned from a compliant to a
            noncompliant state.
            -It is the search method's responsibility to change the state's 
            compliance state variable as the "maintain" and "operate"
            scripts are only called if the state's compliance variable is
            set to True.
            -The search method should use testing criteria to determine if the
            found state is truly in compliance before setting the state's
            compliance variable.
            -The compliance state variable is accessible by calling:
                current_state[<state database path>]['compliance']
            -Any important device setting changes should be propogated to
            their respective databases.
        maintaining:
            -The maintain method should observe the state parameters and
            make any needed adjustments to the state settings in order to
            maintain the state.
            -If time series are needed in order to maintain the state, a
            global variable may be used within the maintain and search
            methods to indicate when the search method brought the state
            into compliance. The maintain method may then use that
            knowledge to selectively pull values from the "monitor" 
            buffers or simply clear the buffers on first pass.
            -The maintain method is responsible for changing the compliance
            variable to False if it is unable to maintain the state.
            -The compliance state variable is accessible by calling:
                current_state[<state database path>]['compliance']
            -Any important device setting changes should be propogated to
            their respective databases.
        operating:
            -The operate method is a catchall function for use cases that
            are only valid while the state is in compliance. An example
            could be to only read values from an instrument buffer while
            the instrument's data collection state is active.
'''
STATES = {
        'filter_cavity/state':{
                'lock':{
                        'settings':{
                                'filter_cavity/device_PID':{
                                        'proportional_action':True, 'integral_action':True,
                                        'derivative_action':False,
                                        'proportional_gain':-0.2, 'integral_gain':1.0e2,
                                        'upper_output_limit':2.00, 'lower_output_limit':0.00},
                                'filter_cavity/device_HV':{
                                        'y_min_limit':0.00, 'y_max_limit':150.00, 'y_voltage':99.1}},
                        'prerequisites':{
                                'critical':[],
                                'necessary':[],
                                'optional':[]},
                        'routines':{
                                'monitor':monitor, 'search':find_lock,
                                'maintain':keep_lock, 'operate':nothing}},
                'manual':{
                        'settings':{},
                        'prerequisites':{
                                'critical':[],
                                'necessary':[],
                                'optional':[]},
                        'routines':{
                                'monitor':monitor, 'search':transfer_to_manual,
                                'maintain':nothing, 'operate':nothing}},
                'safe':{
                        'settings':{'filter_cavity/device_PID':{'pid_action':False}},
                        'prerequisites':{
                                'critical':[],
                                'necessary':[],
                                'optional':[]},
                        'routines':{
                                'monitor':monitor, 'search':transfer_to_manual,
                                'maintain':lock_disabled, 'operate':nothing}},
                'engineering':{
                        'settings':{},
                        'prerequisites':{
                                'critical':[],
                                'necessary':[],
                                'optional':[]},
                        'routines':{
                                'monitor':nothing, 'search':nothing,
                                'maintain':nothing, 'operate':nothing}}
                        }                        
        }
sm.init_states(STATES)


# %% STATE MACHINE ============================================================

'''Operates the state machine.'''
current_state={}
sm.operate_machine(current_state=current_state, main_loop_interval=0.5)


